
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-10.0"

[[constraint]]
  name = "github.com/kubedev/operator-kit"
  version = "v1.13"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/line/line-bot-sdk-go"
  version = "v6.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  go-tests = true
  unused-packages = false
