apiVersion: v1
kind: Secret
metadata:
  name: division-terminal-channel
type: Opaque
data:
  channelID: MTU1OTUzNDkzMg==
  channelSecret: YzIwYmUwOTBjNjMxMWM3ZjY1ZGExY2I2NGViMGRiOTU=
  channelToken: Vmp5MFRBV0Z1MWdZTytmbzRVQjcyK3hQYTBCSXBETm1wWlVrbkRZRTFRMWl4VDZxbUtiTElQSHRZcHF3QXBWUFdXNm9mUHFtNlJmejJDVUF4SzhoOXppZkpTUmovUE1OQUpYSyswVmd2akVUaFBwblZzcmZIdG56VXFiMEdzTFB2ckFaQTh3WWI1UGVGZ0xWQTE5eTBBZEIwNHQ4OS8xTy93MWNEbnlpbEZVPQ==
---
apiVersion: line.you/v1alpha1
kind: Bot
metadata:
  name: division-terminal
spec:
  logLevel: 3
  expose:
    type: Ngrok
    ngrokToken: 5K6uvZby1ceBugkMuee9C_2hB2dheXEi4hkcwNwxf1h
  channelSecretName: division-terminal-channel
  version: v0.1.0
  selector: # eventbinding selector
    matchLabels:
      division: terminal