apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bots.line.you
spec:
  group: line.you
  version: v1alpha1
  names:
    kind: Bot
    singular: bot
    plural: bots
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: events.line.you
spec:
  group: line.you
  version: v1alpha1
  names:
    kind: Event
    singular: event
    plural: events
  scope: Namespaced
  additionalPrinterColumns:
  - name: Type
    type: string
    description: The event type
    JSONPath: .spec.type
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventbindings.line.you
spec:
  group: line.you
  version: v1alpha1
  names:
    kind: EventBinding
    singular: eventbinding
    plural: eventbindings
  scope: Namespaced
  additionalPrinterColumns:
  - name: Events
    type: string
    description: Subset of bindings
    JSONPath: .subsets[*].binding.name