apiVersion: v1
kind: ServiceAccount
metadata:
  name: bot-operator
  namespace: bot-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - deployments
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - line.you
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bot-operator-role
subjects:
- kind: ServiceAccount
  namespace: bot-system
  name: bot-operator