apiVersion: v1
kind: ServiceAccount
metadata:
  name: bot-admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-admin-role
rules:
- apiGroups:
  - line.you
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bot-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bot-admin-role
subjects:
- kind: ServiceAccount
  namespace: default
  name: bot-admin