apiVersion: v1
kind: Secret
metadata:
  name: hunter-aibo-channel
type: Opaque
data:
  channelID: MTU1ODkyMTA2NQ==
  channelSecret: MzkzNjdjZWZiYTgxYWJlYWJmNDNjNTFkMjFmZmIwMjM=
  channelToken: L1IreFVwSVZaNW5BazZUZ2tIcHhQdmQrUkt3aVdhVENqOS9Pc3YvaUt1MHl6U2MwWUJHMXB0NkpWNThiUTlUazhrVnVaSHN0czFrQkJ6dFNDNEo5c1cxSXhxcnc2c252OUl4WkJCWVNSb1JzaHRCbS96OHRiSFZHSWlIZ2QvOHU4dXV4TXl0VUZpSUxnUERBajlsWFVBZEIwNHQ4OS8xTy93MWNEbnlpbEZVPQ==
---
apiVersion: line.you/v1alpha1
kind: Bot
metadata:
  name: hunter-aibo
spec:
  logLevel: 3
  expose:
    type: Ngrok
    ngrokToken: 3prBi7EH4tDp83vmcZ5h4_5cCzZKNRq7wTQKpmY2tZ7
  channelSecretName: hunter-aibo-channel
  version: v0.1.0
  selector: # eventbinding selector
    matchLabels:
      hunter: monster