apiVersion: line.you/v1alpha1
kind: Event
metadata:
  name: join-event
  labels:
    hunter: monster
spec:
  selector: # eventbinding selector
    matchLabels:
      hunter: monster
  type: join
  messages:
  - type: text
    reply: "Meow~ Meow~ Meow~"